# Generated by Django 4.2.6 on 2023-10-31 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quora.profile'),
        ),
    ]
