# Generated by Django 4.2.6 on 2023-10-31 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quora', '0003_alter_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
