# Generated by Django 4.2.6 on 2023-10-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0004_alter_question_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
